
- Fields: `name`, `email`, `phone` (local 10-digit starting with 9), `orderType`, `message`
- Honeypot: `_honey` (hidden field)
- CAPTCHA: user must type `SWEET`
- Redirects to `thanks.html` after successful submit

**Important:** After finishing testing, confirm the email address in FormSubmit dashboard if necessary.

---

## SEO & Social
- Each page contains meta description and Open Graph tags.
- Replace `og:url` and demo image paths in head if you have a production URL.

---

## Deployment
### GitHub Pages
1. Create a repo, upload all files (don't put them inside a nested folder).
2. Enable Pages: Settings → Pages → Branch: `main` → Folder: `/ (root)`.
3. Visit `https://<your-username>.github.io/<repo-name>/`

### Netlify
- Drag & drop the whole project folder into Netlify Drop.

---

## Customization quick notes
- Replace images in `/images` with your high-res photos.
- Update `meta` descriptions and `og:url` in the head of each HTML file.
- To change CTA text, update the `Try Now` / `.btn` text in HTML.

---

## Credits
Designed & Developed by [Your Name]  
Images via Unsplash (replace with your own)  
Form handling via FormSubmit.co

---

If you want, I can also:
- Add structured data (JSON-LD) for local business / product snippets
- Add Google Analytics or Tag Manager
- Wire up WhatsApp quick-order buttons
